@Proyecto-Final.Server_HostAddress = https://localhost:7268
@Proyecto_Final.Server_HostAddress = http://localhost:5192

GET {{Proyecto_Final.Server_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{Proyecto-Final.Server_HostAddress}}/api/register
Content-Type: application/json

{
  //Respondent
}

###

GET {{Proyecto-Final.Server_HostAddress}}/api/test

###
